export default {
  
  "login": "kritikashrmaa",
  "id": 78639134,
  "node_id": "MDQ6VXNlcjc4NjM5MTM0",
  "avatar_url": "https://avatars.githubusercontent.com/u/78639134?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/kritikashrmaa",
  "html_url": "https://github.com/kritikashrmaa",
  "followers_url": "https://api.github.com/users/kritikashrmaa/followers",
  "following_url": "https://api.github.com/users/kritikashrmaa/following{/other_user}",
                    "gists_url": "https://api.github.com/users/kritikashrmaa/gists{/gist_id}",
                      "starred_url": "https://api.github.com/users/kritikashrmaa/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/kritikashrmaa/subscriptions",
                          "organizations_url": "https://api.github.com/users/kritikashrmaa/orgs",
                            "repos_url": "https://api.github.com/users/kritikashrmaa/repos",
                              "events_url": "https://api.github.com/users/kritikashrmaa/events{/privacy}",
                                "received_events_url": "https://api.github.com/users/kritikashrmaa/received_events",
                                  "type": "User",
                                    "site_admin": false,
                                      "name": "Kritika Sharma",
                                        "company": "Shoolini University",
                                          "blog": "",
                                            "location": null,
                                              "email": null,
                                                "hireable": null,
                                                  "bio": "Coffee + DSA +FrontendDev = <3",
                                                    "twitter_username": null,
                                                      "public_repos": 30,
                                                        "public_gists": 0,
                                                          "followers": 0,
                                                            "following": 0,
                                                              "created_at": "2021-02-06T08:24:45Z",
                                                                "updated_at": "2023-07-17T11:50:35Z"

};
